baseURL = "https://gadzbi.com/"
languageCode = "en-us"
title = "Kacper Nitkiewicz Personal Site"
theme="archie"
copyright = "© Kacper Nitkiewicz"
ignoreErrors = ['error-missing-instagram-accesstoken']
uglyURLs = true

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Fast and Concise [blog for Gadzbi](https://github.com/gadzbi123/personal-website)"
  favicon="/favicon.ico"
  
[params.meta]
  favicon = false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/gadzbi123"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/kacper-nitkiewicz-686b87128/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/GadzbiPL"

[[menu.main]]
name = "Home"
url = "/index.html"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts.html"
weight = 2

[[menu.main]]
name = "About"
url = "/about.html"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags.html"
weight = 4
